# Site settings
title: A New and Great Journey
author:
  name: Jeremy Christopher
  email: gratefulcoder75@gmail.com
description: "My personal Journey."
params:
  background_img: "https://media.discordapp.net/attachments/870171421450596376/890128099893719100/unknown.png?width=806&height=453"

# Build settings
remote_theme: jekyll/minima
