# Site settings
title: A New and Great Journey
author:
  name: Jeremy Christopher
  email: gratefulcoder75@gmail.com
description: "My personal Journey."

# Build settings
remote_theme: mmistakes/jekyll-theme-skinny-bones
